### PR TITLE
Porting to MinGW-w64

### PR DESCRIPTION
**Pull request by bigfatbrowncat**
The target of these changes is to support luni (Java core classes from Android) on Windows. The main problem is the POSIX functions which are (partially) unsupported on Windows. Some of them have replacements in WinAPI, some others don't. 

We tried to avoid modifying Java code of the framework cause Java doesn't have ifdefs ;) The only change we couldn't avoid is adding a static constructor (and a native <code>init()</code> function) to <code>libcore.io.Posix</code> class thus we could initialize WinSock there.

We tried to put any significant changes to a special file named <code>mingw-extensions.cpp</code> and change the original <code>libcore_io_Posix.cpp</code> as few as possible, but unfortunately we had to make some modifications (most of them are related to a different functions signature; for example, in Windows we have unsigned int64 for socket descriptor while under unix we have signed int).

Not everything is supported so far. The first target (which is mostly achieved) is sockets support. We made some tests (https://github.com/bigfatbrowncat/avian-droid-tests.git) that work well with this implementation. The most complicated is SimpleFramework demo (http://www.simpleframework.org) which work like a charm (it's a very tough test - it includes pipes and poll() - two main problems on Windows)

While this work is incomplete yet, it supports many features and includes many code changes, so we want to pull it to your repo and continue the discussion with Google guys about merging it upstream.

<em>We made some additional modifications to Avian - i'm going to pull them to the Avian repo too</em>

This pull request is linked to the issue https://github.com/ReadyTalk/avian/issues/168

### CODE REVIEW

**Comment by JustAMan** [comment]
I'd also want to stress that pipe() implementation that we did actually uses sockets instead of normal file descriptors.

This might be a source for some quirks later on, but the problem here is that normal Windows pipes cannot be set to non-blocking mode, only named pipes can; but named pipes are completely different beasts in terms of behaviour compared to POSIX pipes, so implementing them via sockets that behave very similar in Windows and in POSIX seems logical to me.

**Comment by bigfatbrowncat** [comment]
Small additional commit to fix build without __PROVIDE_FIXMES flag

**Comment by bigfatbrowncat** [comment]
Hi! We are going to continue the implementation process (file I/O is not working well yet).

We will work on the same branch and the new commits will appear here.

Please, let us know if something's unclear in our code cause there is already much work done and we want to correct every problem and merge it as soon as possible.

Maybe you give us some useful advice...

**Comment by dicej** [comment]
@bigfatbrowncat, sorry I haven't responded to this yet -- I've been very busy for the past few days and I haven't had time to look at a big pull request like this.  I'll try to do that sometime this week, though.  Thanks for working on it -- it's really exciting stuff!

**Comment by bigfatbrowncat** [comment]
Great! So we are going to fix OpenSSL Windows build (some problems with libcrypt linkage). File I/O appears to work well at a first glance and we try not to modify this code until you approve the pull request. Then we try to fix the rest of "blacklisted" features.

**Pull request merged**
